### PR TITLE
Update AuPayCategoryType.cs

### PR DESCRIPTION
**Pull request by marcuslensxbert**
Please review supported Category types list on 
https://api.keypay.com.au/australia/reference/pay-category/au-pay-category--post

We are currently experiencing an issue with this.

### CODE REVIEW

**Comment by SergioBAM** [comment]
This is the second time this has happened within a year. I had a pull request for this on the 17th August 2023, with a fix from keypay issued on the 25th August.

**Review by adrianksmith — APPROVED** [review]

**Review by samuelspronk — APPROVED** [review]

**Comment by ThirstyJarek** [comment]
@Blitheness hey is there any chance of getting this merged in soon? Thanks!

**Comment by SergioBAM** [comment]
I've just sent Keypay Support details of this and the URL to these PRs. Hopefully it gets noticed soon.

**Comment by Blitheness** [comment]
Hi both, it's on our radar to get sorted out soon. The difficulty with accepting PRs here is that our API client is automatically generated by an internal tool, so changes would be overwritten anyway when our automations release a new version. I cannot provide timescales right now, but colleagues are doing good work on enhancing the client generator and their changes are being tested internally. We're also looking into the best way of having the API client release with every production release of Payroll that changes the API specification. Please do continue to contact us via the support desk with any queries about the API or this API client as we greatly appreciate your feedback.

@SergioBAM @ThirstyJarek

**Comment by SergioBAM** [comment]
I think notifying people of pending API changes would be a great start. Some sort of notification from Keypay/EH would allow us to prepare for these changes, rather than having our clients or internal monitoring systems notify us on the day.

You did have a dev forum thats since been archived at https://developers.yourpayroll.com.au/ 

Perhaps bring something like that back? We dont need the full forum capabilities but a breaking changes announcement sticky would be helpful.

**Comment by Blitheness** [comment]
Thanks for your patience. The latest release incorporates the requested changes. If you have any feedback on the latest release, please reach out to our support team and we'll do our best to assist.

**Pull request closed without merging**
